// Builds the manual SMS message text for an invoice/receipt. Never includes
// VIN, vehicle specs, or internal notes. The public invoice URL is expected
// to already be generated by the caller before this runs - if it's missing,
// the message degrades to a link-less version, but callers (the Text
// Invoice modal) should gate sending/sharing on having a real link first.

function getFirstName(fullName) {
  if (!fullName) return "there";
  const parts = String(fullName).trim().split(/\s+/);
  return parts[0] || "there";
}

function formatCurrency(amount) {
  const numeric = Number(amount);
  if (!Number.isFinite(numeric)) return null;
  return `$${numeric.toFixed(2)}`;
}

function formatDate(dateValue) {
  if (!dateValue) return null;
  const date = new Date(dateValue);
  if (Number.isNaN(date.getTime())) return null;
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

// invoice: { id, totalAmount, dateCreated, dueDate?, publicUrl }
// customer: { name, phone }
// business: reserved for future use (e.g. shop name); not in the default templates.
export function buildInvoiceSmsMessage(invoice = {}, customer = {}, business = {}) {
  const firstName = getFirstName(customer.name);
  const invoiceNumber = invoice.id || null;
  const total = formatCurrency(invoice.totalAmount);
  const dueDate = formatDate(invoice.dueDate);

  let intro;
  if (invoiceNumber && total) {
    intro = `Hello ${firstName}, your invoice ${invoiceNumber} for ${total} is ready`;
  } else if (total) {
    intro = `Hello ${firstName}, your invoice for ${total} is ready`;
  } else if (invoiceNumber) {
    intro = `Hello ${firstName}, your invoice ${invoiceNumber} is ready`;
  } else {
    intro = `Hello ${firstName}, your invoice is ready`;
  }

  intro += dueDate ? `. Due date: ${dueDate}.` : ":";

  if (invoice.publicUrl) {
    return [
      intro,
      "",
      invoice.publicUrl,
      "",
      "Tap the link to view, print, or download your complete invoice. Thank you.",
    ].join("\n");
  }

  return [intro, "Thank you."].join(" ");
}
